In [1]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [ ]:
label = [1,2,3,4]
countries = ["India","USA","Israel","England"]
pd.Series( countries, label)
family = {"name": "Mittal", "Head": "H M Mittal", "Supremo": "Joycee Mittal", "1stChild": "Sushant", "2ndChild": "Rishabh", "Supremo2.0": "Priyanka" }
pd.Series(family)

name                 Mittal
Head             H M Mittal
Supremo       Joycee Mittal
1stChild            Sushant
2ndChild            Rishabh
Supremo2.0         Priyanka
dtype: object

In [5]:
df = pd.DataFrame(randn(5,4), columns= ["a","b","c","d"])
np.random.seed(101)

In [7]:
df.loc[4]['d']
# df.loc['G1'].loc[2]['B']
df.index.name = 'Num'
print(df)
df[df['c']>0]['b']

            a         b         c         d
Num
0   -1.719766  0.492925  1.206234  0.466007
1   -0.591256  0.664886 -1.395797 -0.291495
2   -0.677679  1.023940  0.248048  0.031284
3   -1.126057  0.054609 -0.082354 -1.220653
4   -1.153466 -0.952573 -0.181569 -0.966074

Num
0    0.492925
2    1.023940
Name: b, dtype: float64

1.  This work is important, finding relation between two attributes(columns)
2.  How one column value changes with other column

In [27]:
d = {
    "A":[1,2, np.nan],
    "B":[2,np.nan, np.nan],
    "C": [2,3,4]
}
df = pd.DataFrame(d,"X Y Z".split())
print(df)
print(df.fillna( value = df.loc["Y","A"] , inplace=True))
print(df)

     A    B  C
X  1.0  2.0  2
Y  2.0  NaN  3
Z  NaN  NaN  4
None
     A    B  C
X  1.0  2.0  2
Y  2.0  2.0  3
Z  2.0  2.0  4

In [44]:
data = {
    "Company":"GOOGLE GOOGLE MSFT MSFT FB FB".split(),
    "Employee": "SAMA RISHABH ROHAN RONIT SHORBIT SUPRIYA".split(),
    "Salary": [3.4, 2.0, 3.5, 5.6, 5.0, 6.0]
}

df = pd.DataFrame(data, [1,2,3,4,5,6])
print(df)

  Company Employee  Salary
1  GOOGLE     SAMA     3.4
2  GOOGLE  RISHABH     2.0
3    MSFT    ROHAN     3.5
4    MSFT    RONIT     5.6
5      FB  SHORBIT     5.0
6      FB  SUPRIYA     6.0

In [64]:
byComp = df.groupby("Company").count()
byComp
# df[["Salary", "Employee"]].sort_values(by="Salary")
df.groupby("Company").describe().loc["FB"]

Salary  count    2.000000
        mean     5.500000
        std      0.707107
        min      5.000000
        25%      5.250000
        50%      5.500000
        75%      5.750000
        max      6.000000
Name: FB, dtype: float64